# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/amber/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),amber)

$(call add-radio-file-sha1-checked,radio/audio_dsp.img,32156e20c74b41ff468306e57b60405e2630c2cc)
$(call add-radio-file-sha1-checked,radio/cam_vpu1.img,5335093a73f249cb382d4fd967faa79308fcc097)
$(call add-radio-file-sha1-checked,radio/cam_vpu2.img,e55827cac7cf36bd5d7b9719482827c8b0f524c2)
$(call add-radio-file-sha1-checked,radio/cam_vpu3.img,274410f27b51b4b4ca1d4aaae29064310f1da8dd)
$(call add-radio-file-sha1-checked,radio/dpm.img,132dd9ef59e64c8ba18a33a9aa3e4428877ea48d)
$(call add-radio-file-sha1-checked,radio/gz.img,0869a36b439c9af70544e13bb0d00017747fa30f)
$(call add-radio-file-sha1-checked,radio/lk.img,2db127ef15cb91ba0fae73ac7385110e202c8f85)
$(call add-radio-file-sha1-checked,radio/logo.img,6c3ae74c591746b6f1355033e94d5b89392e8bf0)
$(call add-radio-file-sha1-checked,radio/mcupm.img,83b5b6ed4af4f7f26f1662fbf552c10773575f5a)
$(call add-radio-file-sha1-checked,radio/md1img.img,5e940cf5e659130fb97235f176a1841327075ef7)
$(call add-radio-file-sha1-checked,radio/pi_img.img,0e28c426712fe43d8b70cba042dd1570a44a8190)
$(call add-radio-file-sha1-checked,radio/preloader_raw.img,4d96cd4909b5979c3ee8463e4c0bb70d23a7e9a4)
$(call add-radio-file-sha1-checked,radio/scp.img,8736e8151337f7e26137f15b59bbb689a9dcf78c)
$(call add-radio-file-sha1-checked,radio/spmfw.img,2c1d795aa1fbe15523365515b31eacf7bdc5989a)
$(call add-radio-file-sha1-checked,radio/sspm.img,f12760988e844636958447dfc66507a8eb5bca8d)
$(call add-radio-file-sha1-checked,radio/tee.img,85184c0484dc6b9ecbace824fcf6f288b25d64b7)

endif
